#!/bin/bash

make -C ../../libft/ re
gcc -Wall -Wextra -Werror -lncurses visualisateur.c ../utils.c ../scrap.c ../init.c ../../libft/libft/get_next_line.c ../../libft/libftprintf.a ./affichage.c -I ../../includes
make -C ../../libft/ fclean
